import { Link } from 'react-router-dom'
import { Brand } from '../components/Navigation'
function Placeholder({ eyebrow, title, description, next }: { eyebrow: string; title: string; description: string; next?: [string, string] }) { return <section className="placeholder page-container"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p>{next && <Link className="button" to={next[1]}>{next[0]} <span>→</span></Link>}</section> }
export const QuestPage = () => <Placeholder eyebrow="Step 01 / AI Quest" title="What are you here to build?" description="Your guided quest will turn an outcome into a precise model brief." next={['Shape my AI DNA', '/dna']} />
export const DnaProfilePage = () => <Placeholder eyebrow="Step 02 / AI DNA" title="Give your priorities a signal." description="Balance accuracy, speed, cost, privacy, and ease of use to form your AI DNA." next={['Open the arena', '/arena']} />
export const ArenaPage = () => <Placeholder eyebrow="Step 03 / Arena" title="Let the contenders compete." description="Your shortlisted models will battle against your personal AI DNA." next={['View result', '/result']} />
export const ResultPage = () => <Placeholder eyebrow="Step 04 / Trust Score" title="A winner, with receipts." description="Explore a transparent score that shows why this model is the right match." next={['Get model passport', '/passport']} />
export const PassportPage = () => <Placeholder eyebrow="Step 05 / Model Passport" title="Your model's proof of fit." description="A portable, shareable record of its strengths, score, and winning rationale." next={['Configure deployment', '/deployment']} />
export const DeploymentPage = () => <Placeholder eyebrow="Step 06 / Deployment" title="Ready for the real world." description="Generate the configuration that takes your winning model from arena to application." />
function AuthPage({ signup }: { signup?: boolean }) { return <section className="auth-page"><Brand /><div className="auth-card"><p className="eyebrow">{signup ? 'Create your profile' : 'Welcome back'}</p><h1>{signup ? 'Claim your place.' : 'Return to the arena.'}</h1>{signup && <input placeholder="Your name" />}<input placeholder="Email address" type="email" /><input placeholder="Password" type="password" /><button className="button">{signup ? 'Enter the arena' : 'Log in'} <span>→</span></button><p>{signup ? 'Already a challenger?' : 'New challenger?'} <Link to={signup ? '/login' : '/signup'}>{signup ? 'Log in' : 'Create an account'}</Link></p></div></section> }
export const LoginPage = () => <AuthPage />
export const SignUpPage = () => <AuthPage signup />
